"""Button platform for BTicino Hometouch."""
from __future__ import annotations

import logging
from typing import Any

from homeassistant.components.button import ButtonEntity, ButtonDeviceClass
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import BticinoCoordinator
from .sip_client import MediaMode

_LOGGER = logging.getLogger(__name__)



async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up BTicino Hometouch buttons."""
    coordinator: BticinoCoordinator = hass.data[DOMAIN][entry.entry_id]

    entities: list[ButtonEntity] = []

    # Add door lock buttons
    for lock_id in range(1, coordinator.num_locks + 1):
        entities.append(BticinoDoorLockButton(coordinator, entry, lock_id))

    # Add call control buttons
    entities.append(BticinoHangupCallButton(coordinator, entry))

    # Add video call button for each outdoor station
    for station_id in range(1, coordinator.num_cameras + 1):
        entities.append(BticinoViewVideoButton(coordinator, entry, station_id))

    # Audio button removed - audio is not supported by BTicino gateway

    async_add_entities(entities)


class BticinoDoorLockButton(CoordinatorEntity, ButtonEntity):
    """Button to unlock a door."""

    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: BticinoCoordinator,
        entry: ConfigEntry,
        lock_id: int,
    ) -> None:
        """Initialize the button."""
        super().__init__(coordinator)
        self._lock_id = lock_id
        self._attr_unique_id = f"{entry.entry_id}_lock_{lock_id}"
        self._attr_name = f"Unlock Door {lock_id}"
        self._attr_icon = "mdi:door-open"
        # entity_id is auto-generated by HA based on unique_id

    @property
    def device_info(self) -> DeviceInfo:
        """Return device info."""
        return DeviceInfo(
            identifiers={(DOMAIN, self.coordinator.entry.entry_id)},
            name="BTicino Hometouch",
            manufacturer="BTicino",
            model="Door Entry Touch",
        )

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        """Return extra state attributes."""
        return {
            "lock_id": self._lock_id,
        }

    async def async_press(self) -> None:
        """Handle button press."""
        _LOGGER.info("Unlocking door %d", self._lock_id)
        success = await self.coordinator.async_unlock_door(self._lock_id)
        if not success:
            _LOGGER.error("Failed to unlock door %d", self._lock_id)


class BticinoHangupCallButton(CoordinatorEntity, ButtonEntity):
    """Button to hangup a call."""

    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: BticinoCoordinator,
        entry: ConfigEntry,
    ) -> None:
        """Initialize the button."""
        super().__init__(coordinator)
        self._attr_unique_id = f"{entry.entry_id}_hangup_call"
        self._attr_name = "Hangup Call"
        self._attr_icon = "mdi:phone-hangup"

    @property
    def device_info(self) -> DeviceInfo:
        """Return device info."""
        return DeviceInfo(
            identifiers={(DOMAIN, self.coordinator.entry.entry_id)},
            name="BTicino Hometouch",
            manufacturer="BTicino",
            model="Door Entry Touch",
        )

    @property
    def available(self) -> bool:
        """Return True if there's an active call."""
        return self.coordinator.has_active_call

    async def async_press(self) -> None:
        """Handle button press."""
        _LOGGER.info("Hanging up call")
        success = await self.coordinator.async_hangup_call()
        if not success:
            _LOGGER.error("Failed to hangup call")


class BticinoViewVideoButton(CoordinatorEntity, ButtonEntity):
    """Button to view video from outdoor station."""

    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: BticinoCoordinator,
        entry: ConfigEntry,
        station_id: int,
    ) -> None:
        """Initialize the button."""
        super().__init__(coordinator)
        self._station_id = station_id
        self._attr_unique_id = f"{entry.entry_id}_view_video_{station_id}"
        self._attr_name = f"View Video Station {station_id}"
        self._attr_icon = "mdi:doorbell-video"

    @property
    def device_info(self) -> DeviceInfo:
        """Return device info."""
        return DeviceInfo(
            identifiers={(DOMAIN, self.coordinator.entry.entry_id)},
            name="BTicino Hometouch",
            manufacturer="BTicino",
            model="Door Entry Touch",
        )

    @property
    def available(self) -> bool:
        """Return True if no call is in progress."""
        return self.coordinator.is_registered and not self.coordinator.has_active_call

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        """Return extra state attributes."""
        return {
            "station_id": self._station_id,
        }

    async def async_press(self) -> None:
        """Handle button press - initiate video-only call (audio not supported)."""
        _LOGGER.info("Starting video call to station %d", self._station_id)
        success = await self.coordinator.async_initiate_call(
            self._station_id,
            MediaMode.VIDEO_ONLY
        )
        if success:
            _LOGGER.info("Video call started to station %d", self._station_id)
        else:
            _LOGGER.error("Failed to start video call to station %d", self._station_id)


# BticinoEnableAudioButton removed - audio is not supported by BTicino gateway
# The gateway systematically rejects audio SDP offers from non-Linphone clients
