"""Camera platform for BTicino Hometouch - On-demand video streaming."""
from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any

from homeassistant.components.camera import Camera, CameraEntityFeature
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import BticinoCoordinator, IntercomState
from .sip_client import MediaMode

_LOGGER = logging.getLogger(__name__)

# HLS output directory (must match media_proxy.py)
HLS_OUTPUT_DIR = "/config/www/bticino"



async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up BTicino Hometouch cameras."""
    coordinator: BticinoCoordinator = hass.data[DOMAIN][entry.entry_id]

    entities: list[Camera] = []

    # Add camera entities for each outdoor station
    for camera_id in range(1, coordinator.num_cameras + 1):
        entities.append(BticinoIntercomCamera(coordinator, entry, camera_id))

    async_add_entities(entities)


class BticinoIntercomCamera(CoordinatorEntity, Camera):
    """On-demand camera entity for BTicino Hometouch.

    This camera automatically initiates a SIP call when the stream is requested,
    providing on-demand video access to outdoor stations.
    """

    _attr_has_entity_name = True
    # Note: We intentionally do NOT include CameraEntityFeature.STREAM
    # because HA would automatically call stream_source() on startup,
    # triggering unwanted calls to the intercom. Instead, streaming is
    # handled manually via the custom card which calls our button entities.
    _attr_supported_features = CameraEntityFeature.ON_OFF

    def __init__(
        self,
        coordinator: BticinoCoordinator,
        entry: ConfigEntry,
        camera_id: int,
    ) -> None:
        """Initialize the camera."""
        super().__init__(coordinator)
        Camera.__init__(self)
        self._camera_id = camera_id
        self._attr_unique_id = f"{entry.entry_id}_camera_{camera_id}"
        self._attr_name = f"Camera {camera_id}"
        self._attr_is_streaming = False
        self._last_image: bytes | None = None
        self._call_initiated_by_us = False
        # Force specific entity_id regardless of device name
        self.entity_id = f"camera.bticino_hometouch_camera_{camera_id}"

    @property
    def device_info(self) -> DeviceInfo:
        """Return device info."""
        return DeviceInfo(
            identifiers={(DOMAIN, self.coordinator.entry.entry_id)},
            name="BTicino Hometouch",
            manufacturer="BTicino",
            model="Door Entry Touch",
        )

    @property
    def is_on(self) -> bool:
        """Return True if this camera is active."""
        return self.coordinator.active_camera == self._camera_id

    @property
    def available(self) -> bool:
        """Return True if entity is available (SIP registered)."""
        return self.coordinator.is_registered

    @property
    def is_recording(self) -> bool:
        """Return True if there's an active call to this station."""
        return self.coordinator.has_active_call and self.coordinator.active_camera == self._camera_id

    @property
    def motion_detection_enabled(self) -> bool:
        """Return True if motion detection is enabled (incoming call = motion)."""
        state = self.coordinator.get_station_state(self._camera_id)
        return state == IntercomState.RINGING

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        """Return extra state attributes."""
        state = self.coordinator.get_station_state(self._camera_id)
        last_error = self.coordinator.get_last_error(self._camera_id)
        attrs = {
            "station_id": self._camera_id,
            "station_state": state.value,
            "is_ringing": state == IntercomState.RINGING,
            "is_connected": state == IntercomState.CONNECTED,
            "on_demand": True,
            "hls_available": self._hls_file_exists(),
            "last_error": last_error,
        }
        # Only include hls_url if file exists
        if self._hls_file_exists():
            attrs["hls_url"] = self._get_stream_url()
        return attrs

    def _get_stream_url(self) -> str:
        """Get the HLS stream URL.

        HLS files are generated by ffmpeg to /config/www/bticino/
        and served by HA's built-in web server via /local/bticino/

        Returns a full URL that can be used by the browser.
        """
        # HLS URL path - HA serves /config/www/ content via /local/
        return f"/local/bticino/bticino_camera_{self._camera_id}.m3u8"

    def _hls_file_exists(self) -> bool:
        """Check if the HLS stream is available.

        This uses the coordinator's cached state instead of doing filesystem I/O,
        which would block the event loop.
        """
        return self.coordinator.get_hls_available(self._camera_id)

    async def _wait_for_hls_file(self, timeout: float = 10.0) -> bool:
        """Wait for HLS file to be created with timeout.

        Returns True if file exists or was created within timeout.
        """
        hls_path = Path(HLS_OUTPUT_DIR) / f"bticino_camera_{self._camera_id}.m3u8"
        start_time = asyncio.get_event_loop().time()

        while (asyncio.get_event_loop().time() - start_time) < timeout:
            if hls_path.exists():
                # Also check if file has content (at least one segment reference)
                try:
                    content = hls_path.read_text()
                    if ".ts" in content:  # Has at least one segment
                        _LOGGER.debug("HLS file ready: %s", hls_path)
                        return True
                except Exception:
                    pass
            await asyncio.sleep(0.5)

        _LOGGER.warning("Timeout waiting for HLS file: %s", hls_path)
        return False

    async def async_camera_image(
        self, width: int | None = None, height: int | None = None
    ) -> bytes | None:
        """Return a still image from the camera.

        This is an on-demand camera - if no call is active, we initiate one.
        """
        # If there's already an active call to this station, return cached image
        if self.coordinator.has_active_call and self.coordinator.active_camera == self._camera_id:
            if self._last_image:
                return self._last_image
            # TODO: Capture frame from stream
            return self._generate_placeholder_image("In chiamata...")

        # If no active call, initiate one to get the video
        if not self.coordinator.has_active_call:
            _LOGGER.info("On-demand: initiating call to station %d", self._camera_id)
            self._call_initiated_by_us = True
            success = await self.coordinator.async_initiate_call(self._camera_id, MediaMode.VIDEO_ONLY)
            if not success:
                _LOGGER.warning("Failed to initiate on-demand call to station %d", self._camera_id)
                return self._generate_placeholder_image("Errore connessione")

            # Wait a bit for the call to establish
            await asyncio.sleep(2)

        # If call is active but for a different camera, switch to this one
        elif self.coordinator.active_camera != self._camera_id:
            _LOGGER.info("Switching to camera %d", self._camera_id)
            await self.coordinator.async_switch_camera(self._camera_id)
            await asyncio.sleep(1)

        # Return placeholder while stream is establishing
        return self._generate_placeholder_image("Connessione...")

    def _generate_placeholder_image(self, text: str = "Premi per visualizzare") -> bytes:
        """Generate a simple placeholder image."""
        # Create a minimal 1x1 gray JPEG as placeholder
        # Real images will come from the stream when a call is active
        return bytes([
            0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01,
            0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xFF, 0xDB, 0x00, 0x43,
            0x00, 0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07, 0x07, 0x07, 0x09,
            0x09, 0x08, 0x0A, 0x0C, 0x14, 0x0D, 0x0C, 0x0B, 0x0B, 0x0C, 0x19, 0x12,
            0x13, 0x0F, 0x14, 0x1D, 0x1A, 0x1F, 0x1E, 0x1D, 0x1A, 0x1C, 0x1C, 0x20,
            0x24, 0x2E, 0x27, 0x20, 0x22, 0x2C, 0x23, 0x1C, 0x1C, 0x28, 0x37, 0x29,
            0x2C, 0x30, 0x31, 0x34, 0x34, 0x34, 0x1F, 0x27, 0x39, 0x3D, 0x38, 0x32,
            0x3C, 0x2E, 0x33, 0x34, 0x32, 0xFF, 0xC0, 0x00, 0x0B, 0x08, 0x00, 0x01,
            0x00, 0x01, 0x01, 0x01, 0x11, 0x00, 0xFF, 0xC4, 0x00, 0x1F, 0x00, 0x00,
            0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
            0x09, 0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x10, 0x00, 0x02, 0x01, 0x03,
            0x03, 0x02, 0x04, 0x03, 0x05, 0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7D,
            0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06,
            0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xA1, 0x08,
            0x23, 0x42, 0xB1, 0xC1, 0x15, 0x52, 0xD1, 0xF0, 0x24, 0x33, 0x62, 0x72,
            0x82, 0x09, 0x0A, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x25, 0x26, 0x27, 0x28,
            0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x43, 0x44, 0x45,
            0x46, 0x47, 0x48, 0x49, 0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59,
            0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x73, 0x74, 0x75,
            0x76, 0x77, 0x78, 0x79, 0x7A, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89,
            0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0xA2, 0xA3,
            0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6,
            0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9,
            0xCA, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2,
            0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF1, 0xF2, 0xF3, 0xF4,
            0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01,
            0x00, 0x00, 0x3F, 0x00, 0xFB, 0xD5, 0xFF, 0xD9
        ])

    async def stream_source(self) -> str | None:
        """Return the stream source URL.

        IMPORTANT: This method does NOT initiate calls automatically.
        Calls should be initiated via button entities (View Video Station X).
        This method only returns the HLS URL if a stream is already active.

        This prevents HA from automatically calling all intercoms on startup.
        """
        # Only return URL if there's an active call to THIS station and HLS exists
        if (self.coordinator.has_active_call and
            self.coordinator.active_camera == self._camera_id and
            self._hls_file_exists()):
            return self._get_stream_url()

        # No active call or wrong camera - return None (don't start a call!)
        return None

    @property
    def frontend_stream_type(self) -> str | None:
        """Return the type of stream for the frontend."""
        # Always return HLS for compatibility
        return "hls"

    async def async_turn_on(self) -> None:
        """Turn on the camera - initiate call to this station."""
        if self.coordinator.has_active_call:
            if self.coordinator.active_camera != self._camera_id:
                await self.coordinator.async_switch_camera(self._camera_id)
                _LOGGER.info("Switched to camera %d", self._camera_id)
        else:
            self._call_initiated_by_us = True
            await self.coordinator.async_initiate_call(self._camera_id, MediaMode.VIDEO_ONLY)
            _LOGGER.info("Initiated on-demand call to station %d", self._camera_id)

    async def async_turn_off(self) -> None:
        """Turn off the camera - hangup call."""
        if self.coordinator.has_active_call:
            await self.coordinator.async_hangup_call()
            self._call_initiated_by_us = False
            _LOGGER.info("Ended call from camera turn off")
